name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh user@server-ip "cd /c/Users/White_sama/fastapi-book-project && git pull origin main && systemctl restart fastapi.service"
